sudo: required
language: c
os:
        - linux
addons:
        apt:
                packages:
                        - curl
before_install:
        - sudo apt-get update -qq
        - sudo apt-get install python3-pip
        - wget https://github.com/ncw/rclone/releases/download/v1.45/rclone-v1.45-linux-amd64.deb -O rclone.deb
        - sudo dpkg -i rclone.deb
        - cp -a .config $HOME
script:
        - pip3 install -U wheel --user
        - pip3 install -U telegram-upload
        - ./.func.sh
after_success:
        - echo done
