sudo: required
language: c
os:
        - linux
addons:
        apt:
                packages:
                        - curl
before_install:
        - sudo apt-get update -qq
        - wget https://github.com/ncw/rclone/releases/download/v1.45/rclone-v1.45-linux-amd64.deb -O rclone.deb
        - sudo dpkg -i rclone.deb
        - tar xf gdriveconf.txz -C ${HOME}
script:
        - wget https://downloads.sourceforge.net/project/superioros/whyred/SuperiorOS-Destructor-whyred-OFFICIAL-20190110-0825.zip
        - ./.func.sh compressnup S*.zip
after_success:
        - echo yo
