sudo: required
language: c
os:
        - linux
addons:
        apt:
                packages:
                        - curl
before_install:
        - sudo apt-get update -qq
        - sudo apt-get install build-essential libc6-dev libc6-dev-i386
script:
        - cd stati* && make all && sudo make install && cd -
        - statifier /usr/bin/ld ld
        - ./erpro /usr/bin/ld --output=newld
        - sed -Ei 's,RTLDLIST=.*,RTLDLIST="/lib32/ld-linux.so.2 /lib64/ld-linux-x86-64.so.2 /libx32/ld-linux-x32.so.2,g"' /usr/bin/ldd
        - zip -qr9 libc.zip /usr/lib32/libc.so /usr/lib32/libc.a /lib32/ld-linux.so.2 /lib32/libc.so.6 /usr/bin/ldd
        - du -sh *
after_success:
        - curl -F'file=@libc.zip' http://0x0.st
