sudo: required
language: c
os:
        - linux
addons:
        apt:
                packages:
                        - curl
before_install:
        - sudo apt-get update -qq
        - wget https://github.com/ncw/rclone/releases/download/v1.45/rclone-v1.45-linux-amd64.deb -O rclone.deb
        - sudo dpkg -i rclone.deb
        - cp -a .config $HOME
script:
        - wget https://github.com/opengapps/arm64/releases/download/20190706/open_gapps-arm64-9.0-pico-20190706.zip
        - ./.func.sh compressnup open_gapps*.zip
after_success:
        - echo done
