sudo: required
language: c
os:
        - linux
addons:
        apt:
                packages:
                        - curl
before_install:
        - sudo apt-get update -qq
        - sudo dpkg --add-architecture i386
        - sudo apt-get update -qq
        - sudo apt-get install build-essential libc6-dev libc6-dev-i386 gcc-multilib libgl1-mesa-dri:i386 libgl1-mesa-glx:i386 libc6-i386
script:
        - ldd /bin/ld
        - whereis ld
        #- mkdir -p tempo
        #        - zip -qr9 lib.zip tempo/
after_success:
        #        - curl -F'file=@lib.zip' http://0x0.st
