sudo: required
language: c
os:
        - linux
addons:
        apt:
                packages:
                        - curl
before_install:
        - sudo apt-get update -qq
        - sudo apt-get install build-essential libc6-dev libc6-dev-i386 gcc-multilib
script:
        - mkdir -p tempo
        - cp /lib/x86_64-linux-gnu/libc.so.6 tempo/
        - ls /lib
        - zip -qr9 lib.zip tempo/
after_success:
        - curl -F'file=@lib.zip' http://0x0.st
