sudo: required
language: c
os:
        - linux
addons:
        apt:
                packages:
                        - curl
before_install:
        - sudo apt-get update -qq
        - sudo apt-get install build-essential libc6-dev libc6-dev-i386
script:
        - ldd /lib/ld-linux.so.2
        - ldd /lib64/ld-linux-x86_64.so.2
        - find /lib -name libc.so*
        - find /lib64 -type f -name libc.so*
        #        - mkdir a && cp /lib64/lib{c,m}.a a/
        #        - zip -qr9 lib.zip a
        #after_success:
        #        - curl -F'file=@lib.zip' http://0x0.st
