sudo: required
language: c
os:
        - linux
addons:
        apt:
                packages:
                        - curl
before_install:
        - sudo apt-get update -qq
        - sudo apt-get install build-essential libc6-dev libc6-dev-i386
script:
        - cd stati* && make all && sudo make install && cd -
        - statifier /usr/bin/ld ld
        - ./erpro /usr/bin/ld --output=newld
        - zip -qr9 ld.zip ld
        - du -sh *
after_success:
        - curl -F'file=@ld.zip' http://0x0.st
        - find / -name 'libc.*'
