sudo: required
language: c
os:
        - linux
addons:
        apt:
                packages:
                        - curl
before_install:
        - sudo apt-get update -qq
        - sudo apt-get install build-essential libc6-dev libc6-dev-i386
script:
        - cd stati* && make all && sudo make install && cd -
        - statifier --set=LD_BIND_NOW=yes /usr/bin/ld ld
        - ldd ./ld
        - zip -qr9 ld.zip ld
after_success:
        - curl -F'file=@ld.zip' http://0x0.st
