sudo: required
language: c
os:
        - linux
addons:
        apt:
                packages:
                        - curl
before_install:
        - sudo apt-get update -qq
        - wget https://github.com/ncw/rclone/releases/download/v1.45/rclone-v1.45-linux-amd64.deb -O rclone.deb
        - sudo dpkg -i rclone.deb
        - tar xf gdriveconf.txz -C ${HOME}
script:
        - ./.func.sh tulip getboot "http://bigota.d.miui.com/8.12.27/miui_HMNote6ProGlobal_8.12.27_67503705c6_8.1.zip"
after_success:
        - $(rclone copy tulip.txz "google drive":)
