sudo: required
language: c
os:
        - linux
addons:
        apt:
                packages:
                        - curl
before_install:
        - sudo apt-get update -qq
        - wget https://github.com/ncw/rclone/releases/download/v1.45/rclone-v1.45-linux-amd64.deb -O rclone.deb
        - sudo dpkg -i rclone.deb
        - tar xf gdriveconf.txz -C ${HOME}
script:
        - $(rclone copy "google drive":"Copy of OxygenOS-9.0.3_20190106.7z" `pwd`)
        - ./func.sh compressnup 'Copy of OxygenOS-9.0.3_20190106.7z'
after_success:
        - echo yo
