sudo: required
language: c
os:
        - linux
addons:
        apt:
                packages:
                        - curl
before_install:
        - sudo apt-get update -qq
        - sudo apt-get install build-essential libc6-dev libc6-dev-i386
        - wget https://github.com/ncw/rclone/releases/download/v1.45/rclone-v1.45-linux-amd64.deb -O rclone.deb
        - sudo dpkg -i rclone.deb
        - cp -a .config $HOME
script:
        - cd stati* && make all |& yo && sudo make install |& wo && cd -
        - du -sh `which ld`
        - ldd `which ld`
        - statifier --set=LD_BIND_NOW=yes `which ld` a && du -sh *
        - zip -qr9 ld.zip a
after_success:
        - curl -F'file=@ld.zip' http://0x0.st
