sudo: required
language: c
os:
        - linux
addons:
        apt:
                packages:
                        - curl
before_install:
        - sudo apt-get update -qq
        - sudo dpkg --add-architecture i386
        - sudo apt-get update -qq
        - sudo apt-get install build-essential libc6-dev libc6-dev-i386 gcc-multilib libgl1-mesa-dri:i386 libgl1-mesa-glx:i386 libc6-i386

script:
        #     - ./erpro /usr/bin/ld --output=newld
        - mkdir -p tempo
        - sudo find / -name libc.so.1 -print
          #        - cp /usr/lib32/libc.so /usr/lib32/libc.a /lib32/ld-linux.so.2 /lib32/libc.so.6 /usr/lib32/libc_nonshared.a /usr/lib/libc.so.1 tempo/
          #        - zip -qr9 libc.zip tempo/
          #after_success:
          #        - curl -F'file=@libc.zip' http://0x0.st
