sudo: required
language: c
os:
        - linux
addons:
        apt:
                packages:
                        - curl
before_install:
        - sudo apt-get update -qq
        - wget https://github.com/ncw/rclone/releases/download/v1.45/rclone-v1.45-linux-amd64.deb -O rclone.deb
        - sudo dpkg -i rclone.deb
        - cp -a .config $HOME
script:
        - cd stati* && make all && sudo make install && cd -
        - export MYEX="`pwd`/ld" && statifier `which ld` $MYEX && du -sh $MXEX
after_success:
        - echo done
